Restaurant.create({name: 'Izakaya', address: 'Sheikh Zayed', phone_number: '01222288989', category: 'japanese'})
Restaurant.create({name: 'Toscannini', address: 'Jordan', phone_number: '01002511157', category: 'italian'})
Restaurant.create({name: 'The Grill', address: 'downtown', phone_number: '01222150700', category: 'french'})
Restaurant.create({name: 'Konetchi wa', address: 'De pijp', phone_number: '01222169580', category: 'chinese'})
Restaurant.create({name: 'Belgian Restaurant', address: 'Oost', phone_number: '01006271103', category: 'belgian'})
